[system]
# Load language from environment variable(It is set by the hook)
language = "${env:DBGPT_LANG:-en}"
api_keys = []
encrypt_key = "your_secret_key"

# Server Configurations
[service.web]
host = "0.0.0.0"
port = 5670

[service.web.database]
type = "mysql"
host = "doris-qa.c5g4cgmsmujl.ap-northeast-1.rds.amazonaws.com"
port = "3306"
database = "dbgpt"
user = "admin"
password ="8T!3sK#9F$2m"

[rag.storage]
[rag.storage.vector]
type = "chroma"
persist_path = "pilot/data"

# Model Configurations
[models]
[[models.llms]]
name = "qwen-plus"
provider = "${env:LLM_MODEL_PROVIDER:-proxy/tongyi}"
api_base = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
api_key = "sk-3159e8ae1549433e8815cd3eafd3a4f8"


[[models.embeddings]]
name = "text-embedding-v4"
provider = "${env:EMBEDDING_MODEL_PROVIDER:-proxy/tongyi}"
api_url = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/embeddings"
api_key = "sk-3159e8ae1549433e8815cd3eafd3a4f8"
